# Generated by Django 4.2.2 on 2023-06-25 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('dealership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyinghistorycustomer',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.car'),
        ),
        migrations.AddField(
            model_name='buyinghistorycustomer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='buyinghistorycustomer',
            name='dealership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.dealership'),
        ),
    ]
