version: '3'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - CarDealership/.env
    ports:
      - 5432:5432
  web:
    build: .
    env_file:
      - CarDealership/.env
    environment:
    - PIPENV_SHELL=bash
    command: sh -c "sleep 10 && pipenv run python CarDealership/manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
    depends_on:
      - db


  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"

  celery:
    build: .
    command: sh -c "cd CarDealership && celery -A CarDealership worker --loglevel=info"


    volumes:
      - .:/usr/src/dilership/
    env_file:
      - CarDealership/.env
    depends_on:
      - web
      - db
      - redis

  refresher:
    build: .
    command: sh -c "cd CarDealership && celery -A CarDealership beat --loglevel=info"
    volumes:
      - .:/usr/src/dilership/
    env_file:
      - CarDealership/.env
    depends_on:
      - celery
      - db
      - redis
