# Generated by Django 4.2.2 on 2023-06-20 13:15

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('balance', models.IntegerField(default=0)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('contact_number', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('amount_of_client', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('balance', models.IntegerField(default=0)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('characteristics', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CarDealership_app.characteristic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('date_start', models.DateTimeField()),
                ('date_finish', models.DateTimeField()),
                ('percentage', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegularVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealership_app.customer')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealership_app.dealership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListOfAutomobilesDealership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealership_app.automobile')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealership_app.dealership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListOfAutomobilesDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(default=0)),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealership_app.automobile')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CarDealership_app.dealer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealership_app.automobile')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealership_app.dealer')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealership_app.dealership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuyingHistoryDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealership_app.automobile')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CarDealership_app.dealer')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealership_app.dealership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuyingHistoryCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealership_app.automobile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealership_app.customer')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealership_app.dealership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='automobile',
            name='characteristics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CarDealership_app.characteristic'),
        ),
        migrations.CreateModel(
            name='PromotionDealership',
            fields=[
                ('promotion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CarDealership_app.promotion')),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealership_app.automobile')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealership_app.dealership')),
            ],
            options={
                'abstract': False,
            },
            bases=('CarDealership_app.promotion',),
        ),
        migrations.CreateModel(
            name='PromotionDealer',
            fields=[
                ('promotion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CarDealership_app.promotion')),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealership_app.automobile')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealership_app.dealer')),
            ],
            options={
                'abstract': False,
            },
            bases=('CarDealership_app.promotion',),
        ),
    ]
