# Generated by Django 4.2.2 on 2023-06-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drivetrain', models.CharField(choices=[('FWD', 'FWD'), ('AWD', 'AWD'), ('RWD', 'RWD'), ('4WD', '4WD')], max_length=10)),
                ('engine', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Electric', 'Electric'), ('Natural', 'Natural'), ('Gas', 'Gas'), ('Hydrogen', 'Hydrogen'), ('LPG', 'LPG'), ('Flex-fuel', 'Flex-fuel')], max_length=10)),
                ('bodytype', models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('MUV', 'MUV'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Pickup', 'Pickup'), ('Truck', 'Truck')], max_length=20)),
                ('transmission', models.CharField(choices=[('automatic', 'automatic'), ('manual', 'manual'), ('CVT', 'CVT')], max_length=10)),
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('date_start', models.DateTimeField()),
                ('date_finish', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('percentage', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
